# Generated by Django 5.1.6 on 2025-05-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mrp', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=500)),
            ],
        ),
    ]
