# Generated by Django 5.1.6 on 2025-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='hello', upload_to='assets'),
            preserve_default=False,
        ),
    ]
