# Generated by Django 5.1.6 on 2025-05-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='about',
        ),
    ]
