# Generated by Django 5.1.6 on 2025-06-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
