# Generated by Django 5.1.6 on 2025-05-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mrp',
            new_name='dis_mrp',
        ),
        migrations.AddField(
            model_name='product',
            name='og_mrp',
            field=models.CharField(default=1499, max_length=50),
            preserve_default=False,
        ),
    ]
