# Generated by Django 5.1.6 on 2025-06-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dis_mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='og_mrp',
        ),
    ]
