# Generated by Django 5.1.6 on 2025-06-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_dis_mrp_remove_product_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='assets'),
            preserve_default=False,
        ),
    ]
