# Generated by Django 5.1.6 on 2025-06-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dis_mrp',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='og_mrp',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
